- name: update homebrew
  community.general.homebrew:
    update_homebrew: true

- name: upgrade homebrew
  community.general.homebrew:
    upgrade_all: true

- name: install homebrew packages
  community.general.homebrew:
    name:
      - bat
      - curl
      - fd
      - fzf
      - gh
      - git
      - jq
      - lsd
      - mas
      - nodenv
      - pipenv
      - safe-rm
      - starship
      - trash-cli
      - tree
      - vim
      - wget
      - zsh
